"""
Configuration settings for Agentic AI features
"""
import os
from pathlib import Path

# Base paths
BASE_DIR = Path(__file__).parent.parent
AGENTIC_DIR = Path(__file__).parent
MODELS_DIR = BASE_DIR / 'models'
REPORTS_DIR = BASE_DIR / 'reports'
SHAP_DIR = REPORTS_DIR / 'shap'

# Create directories if they don't exist
REPORTS_DIR.mkdir(exist_ok=True)
SHAP_DIR.mkdir(exist_ok=True)

# Model paths - Using OpenSMILE + XGBoost (Best Accuracy: ~90%)
PRIMARY_MODEL_PATH = MODELS_DIR / 'xgboost_opensmile_20251108_154914.json'
SCALER_PATH = MODELS_DIR / 'scaler_20251108_154914.pkl'


# Gemini API Configuration
# GET YOUR API KEY FROM: https://makersuite.google.com/app/apikey
# PASTE IT BELOW (replace 'PASTE_YOUR_GEMINI_API_KEY_HERE')
GEMINI_API_KEY = 'AIzaSyAF4-72TvD-5LjaRKoO2d6k3g6gTu_TheY'  # ← PUT YOUR API KEY HERE
GEMINI_MODEL = 'gemini-2.0-flash'  # Using latest fast model

# SHAP Configuration
SHAP_NUM_SAMPLES = 100  # Number of samples for SHAP explanation
SHAP_BACKGROUND_SIZE = 50  # Background dataset size

# Audio Quality Thresholds
MIN_AUDIO_QUALITY = 0.65  # Minimum acceptable audio quality score
QUALITY_WARNING_THRESHOLD = 0.75  # Threshold for quality warning

# Risk Score Thresholds (Calibrated for OpenSMILE+XGBoost model)
LOW_RISK_THRESHOLD = 0.40
MODERATE_RISK_THRESHOLD = 0.70  # This is the conservative threshold we tested

# History Configuration
MAX_HISTORY_DISPLAY = 10  # Maximum number of tests to show in history
TREND_ANALYSIS_WINDOW = 3  # Number of recent tests for trend analysis

# Report Configuration
REPORT_TITLE = "Voice-Based Parkinson's Screening Report"
CLINIC_NAME = "VoiceCare AI Health Center"
REPORT_DISCLAIMER = (
    "This report is generated by an AI-assisted screening tool and is not a medical diagnosis. "
    "Please consult a qualified healthcare professional for proper evaluation."
)

# Gemini Persona Configuration
GEMINI_SYSTEM_PROMPT = """You are an empathetic telemedicine assistant specializing in neurological health.
Your role is to interpret voice analysis results in a gentle, comforting tone.
Guidelines:
- Use simple, non-clinical language
- Be empathetic and reassuring
- Focus on observed patterns, not diagnoses
- Encourage professional consultation when appropriate
- Keep responses concise (2-3 sentences)
- Never provide medical advice or diagnosis
"""

# Feature extraction parameters
MEL_SPEC_PARAMS = {
    'n_mels': 128,
    'hop_length': 512,
    'n_fft': 2048,
    'fmax': 8000
}

# Acoustic features to track
KEY_ACOUSTIC_FEATURES = [
    'pitch_variability',
    'amplitude_stability',
    'spectral_centroid',
    'zero_crossing_rate',
    'mfcc_variance',
    'jitter',
    'shimmer',
    'harmonics_to_noise_ratio'
]
